; ============================================================
;  HidroSopó — PlatformIO
;  Instalar: pip install platformio    (o extensión de VS Code)
;  Compilar: pio run
;  Cargar:   pio run -t upload
;  Monitor:  pio device monitor
; ============================================================

[env:heltec_wifi_lora_32_V3]
platform      = espressif32
board         = heltec_wifi_lora_32_V3
framework     = arduino
monitor_speed = 115200
upload_speed  = 921600

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=1

lib_deps =
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0
    adafruit/Adafruit SHT31 Library @ ^2.2.2
    adafruit/Adafruit BusIO @ ^1.16.1
    bblanchon/ArduinoJson @ ^7.1.0
    jgromes/RadioLib @ ^7.0.0

; ---- Variante ESP32 DevKit + módulo LoRa externo (opción económica) ----
[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200
build_flags   = -D PLACA_GENERICA=1
lib_deps      = ${env:heltec_wifi_lora_32_V3.lib_deps}
